using Pho.Domain.Contracts;
using Pho.Domain.Identity;
using UnityEngine;

namespace Pho.Data
{
    /// <summary>
    /// Static ingredient definition. Implements the frozen
    /// <see cref="IIngredientDef"/> contract exactly; adds two Unity-only
    /// extras (worldPrefab, icon) that are NOT on the interface because pure
    /// Domain logic never needs visuals.
    ///
    /// Instances live under Assets/Content/Ingredients/&lt;id&gt;.asset and are
    /// generated by Pho.EditorTools.Content.ContentGenerator from
    /// ContentManifest -- never hand-authored.
    /// </summary>
    [CreateAssetMenu(menuName = "Pho/Ingredient", fileName = "NewIngredient")]
    public sealed class IngredientData : ScriptableObject, IIngredientDef
    {
        [SerializeField] string id;                    // "ing.beef_brisket" -- must match filename exactly
        [SerializeField] string displayName;
        [SerializeField] IngredientCategory category;
        [SerializeField] float basePurchasePrice;       // per unit
        [SerializeField] float baseQuality01;            // 0..1
        [SerializeField] float shelfLifeHours;
        [SerializeField] StorageRequirement storage;
        [SerializeField] int unitsPerCrate;

        // Unity-only, deliberately absent from IIngredientDef -- see doc section 2.2.
        [SerializeField] GameObject worldPrefab;
        [SerializeField] Sprite icon;

        /// <summary>Raw serialized id string, for content-validation tooling (filename/regex checks).</summary>
        public string RawId => id;

        public IngredientId Id => new IngredientId(id);
        public string DisplayName => displayName;
        public IngredientCategory Category => category;
        public float BasePurchasePrice => basePurchasePrice;
        public float BaseQuality01 => baseQuality01;
        public float ShelfLifeHours => shelfLifeHours;
        public StorageRequirement Storage => storage;
        public int UnitsPerCrate => unitsPerCrate;

        public GameObject WorldPrefab => worldPrefab;
        public Sprite Icon => icon;

#if UNITY_EDITOR
        /// <summary>
        /// Editor-only initializer used exclusively by ContentGenerator to
        /// write/refresh this asset from ContentManifest. Never called at
        /// runtime; visuals (worldPrefab/icon) are intentionally not set here
        /// -- prefab/scene generation is a separate, later pass.
        /// </summary>
        public void EditorInit(
            string id,
            string displayName,
            IngredientCategory category,
            float basePurchasePrice,
            float baseQuality01,
            float shelfLifeHours,
            StorageRequirement storage,
            int unitsPerCrate)
        {
            this.id = id;
            this.displayName = displayName;
            this.category = category;
            this.basePurchasePrice = basePurchasePrice;
            this.baseQuality01 = baseQuality01;
            this.shelfLifeHours = shelfLifeHours;
            this.storage = storage;
            this.unitsPerCrate = unitsPerCrate;
        }
#endif
    }
}
